config-version: 2
name: 'netsuite'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
    netsuite:
        materialized: table
        intermediate:
            materialized: ephemeral