{% macro get_vendors_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "account_owner", "datatype": dbt.type_string()},
    {"name": "accountnumber", "datatype": dbt.type_string()},
    {"name": "accounts_email", "datatype": dbt.type_string()},
    {"name": "annual_revenue", "datatype": dbt.type_float()},
    {"name": "auto_renewals", "datatype": dbt.type_string()},
    {"name": "auto_send_statements", "datatype": dbt.type_string()},
    {"name": "billaddress", "datatype": dbt.type_string()},
    {"name": "billing_class_id", "datatype": dbt.type_float()},
    {"name": "city", "datatype": dbt.type_string()},
    {"name": "comments", "datatype": dbt.type_string()},
    {"name": "companyname", "datatype": dbt.type_string()},
    {"name": "country", "datatype": dbt.type_string()},
    {"name": "create_date", "datatype": dbt.type_timestamp()},
    {"name": "creditlimit", "datatype": dbt.type_float()},
    {"name": "currency_id", "datatype": dbt.type_float()},
    {"name": "date_deleted", "datatype": dbt.type_timestamp()},
    {"name": "date_last_modified", "datatype": dbt.type_timestamp()},
    {"name": "dic", "datatype": dbt.type_string()},
    {"name": "email", "datatype": dbt.type_string()},
    {"name": "email_bill_payment_vouchers", "datatype": dbt.type_string()},
    {"name": "email_cash_sales", "datatype": dbt.type_string()},
    {"name": "email_credit_notes", "datatype": dbt.type_string()},
    {"name": "email_invoices", "datatype": dbt.type_string()},
    {"name": "email_item_fulfilments", "datatype": dbt.type_string()},
    {"name": "email_purchase_orders", "datatype": dbt.type_string()},
    {"name": "email_quotes", "datatype": dbt.type_string()},
    {"name": "email_sales_orders", "datatype": dbt.type_string()},
    {"name": "email_statements", "datatype": dbt.type_string()},
    {"name": "employee_number", "datatype": dbt.type_string()},
    {"name": "exemption_certificate_no", "datatype": dbt.type_string()},
    {"name": "expense_account_id", "datatype": dbt.type_float()},
    {"name": "fax", "datatype": dbt.type_string()},
    {"name": "full_name", "datatype": dbt.type_string()},
    {"name": "home_phone", "datatype": dbt.type_string()},
    {"name": "hris_id", "datatype": dbt.type_string()},
    {"name": "ico", "datatype": dbt.type_string()},
    {"name": "id_number_in_the_country_of_r", "datatype": dbt.type_string()},
    {"name": "id_type_in_the_country_of_r_id", "datatype": dbt.type_float()},
    {"name": "in_transit_balance", "datatype": dbt.type_float()},
    {"name": "incoterm", "datatype": dbt.type_string()},
    {"name": "industry_id", "datatype": dbt.type_float()},
    {"name": "invoice_via_procurement_syste", "datatype": dbt.type_string()},
    {"name": "invoicing_details", "datatype": dbt.type_string()},
    {"name": "is1099eligible", "datatype": dbt.type_string()},
    {"name": "is_partner", "datatype": dbt.type_string()},
    {"name": "is_person", "datatype": dbt.type_string()},
    {"name": "isemailhtml", "datatype": dbt.type_string()},
    {"name": "isemailpdf", "datatype": dbt.type_string()},
    {"name": "isinactive", "datatype": dbt.type_string()},
    {"name": "labor_cost", "datatype": dbt.type_float()},
    {"name": "last_modified_date", "datatype": dbt.type_timestamp()},
    {"name": "last_sales_activity", "datatype": dbt.type_timestamp()},
    {"name": "line1", "datatype": dbt.type_string()},
    {"name": "line2", "datatype": dbt.type_string()},
    {"name": "line3", "datatype": dbt.type_string()},
    {"name": "loginaccess", "datatype": dbt.type_string()},
    {"name": "lsa_link", "datatype": dbt.type_string()},
    {"name": "lsa_link_name", "datatype": dbt.type_string()},
    {"name": "mobile_phone", "datatype": dbt.type_string()},
    {"name": "msa_effective_date", "datatype": dbt.type_timestamp()},
    {"name": "name", "datatype": dbt.type_string()},
    {"name": "no__of_employees", "datatype": dbt.type_float()},
    {"name": "openbalance", "datatype": dbt.type_float()},
    {"name": "openbalance_foreign", "datatype": dbt.type_float()},
    {"name": "payables_account_id", "datatype": dbt.type_float()},
    {"name": "payment_terms_id", "datatype": dbt.type_float()},
    {"name": "phone", "datatype": dbt.type_string()},
    {"name": "prepayment_balance", "datatype": dbt.type_float()},
    {"name": "printoncheckas", "datatype": dbt.type_string()},
    {"name": "purchaseorderamount", "datatype": dbt.type_float()},
    {"name": "purchaseorderquantity", "datatype": dbt.type_float()},
    {"name": "purchaseorderquantitydiff", "datatype": dbt.type_float()},
    {"name": "purchases_email", "datatype": dbt.type_string()},
    {"name": "receiptamount", "datatype": dbt.type_float()},
    {"name": "receiptquantity", "datatype": dbt.type_float()},
    {"name": "receiptquantitydiff", "datatype": dbt.type_float()},
    {"name": "represents_subsidiary_id", "datatype": dbt.type_float()},
    {"name": "restrict_access_to_expensify", "datatype": dbt.type_string()},
    {"name": "salesforce_id", "datatype": dbt.type_string()},
    {"name": "shipaddress", "datatype": dbt.type_string()},
    {"name": "shipping_email", "datatype": dbt.type_string()},
    {"name": "state", "datatype": dbt.type_string()},
    {"name": "subsidiary", "datatype": dbt.type_float()},
    {"name": "tax_contact_first_name", "datatype": dbt.type_string()},
    {"name": "tax_contact_id", "datatype": dbt.type_float()},
    {"name": "tax_contact_last_name", "datatype": dbt.type_string()},
    {"name": "tax_contact_middle_name", "datatype": dbt.type_string()},
    {"name": "tax_number", "datatype": dbt.type_string()},
    {"name": "taxidnum", "datatype": dbt.type_string()},
    {"name": "time_approver_id", "datatype": dbt.type_float()},
    {"name": "transactions_need_approval", "datatype": dbt.type_string()},
    {"name": "uen", "datatype": dbt.type_string()},
    {"name": "unbilled_orders", "datatype": dbt.type_float()},
    {"name": "unbilled_orders_foreign", "datatype": dbt.type_float()},
    {"name": "url", "datatype": dbt.type_string()},
    {"name": "vat_registration_no", "datatype": dbt.type_string()},
    {"name": "vendor_extid", "datatype": dbt.type_string()},
    {"name": "vendor_id", "datatype": dbt.type_float()},
    {"name": "vendor_type_id", "datatype": dbt.type_float()},
    {"name": "zipcode", "datatype": dbt.type_string()}
] %}

{{ fivetran_utils.add_pass_through_columns(columns, var('vendors_pass_through_columns')) }}

{{ return(columns) }}

{% endmacro %}

{% macro get_netsuite2_vendors_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "altname", "datatype": dbt.type_string()},
    {"name": "category", "datatype": dbt.type_int()},
    {"name": "companyname", "datatype": dbt.type_string()},
    {"name": "datecreated", "datatype": dbt.type_timestamp()},
    {"name": "entityid", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_int()}
] %}

{{ fivetran_utils.add_pass_through_columns(columns, var('vendors_pass_through_columns')) }}

{{ return(columns) }}

{% endmacro %}
